#!/usr/bin/env bash

git remote set-url origin "https://ylixir:$GITHUB_TOKEN@github.com/ylixir/phap.git" > /dev/null 2>&1

if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]
then
    echo Making release
    ./go tag
    curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=ylixir&apiToken=$PACKAGIST_TOKEN" -d'{"repository":{"url":"https://packagist.org/packages/ylixir/phap"}}' > /dev/null 2>&1
else
    echo Not making release for "$TRAVIS_BRANCH" and pull request "$TRAVIS_PULL_REQUEST"
fi